<?php require('template/header.phtml');
if($userTableDataSet->checkIfStudent($_SESSION['user_id'])) {
?>
<h2>Student</h2>
    <form method="post" action="" class="form text-primary" enctype="multipart/form-data">
        <div class="form-group">
            <label for="studentEmail">Email *</label>
            <input type="email" class="form-control" placeholder="Email" name="studentEmail" required>
        </div>
        <div class="form-group">
            <label for="studentPassword">Password *</label>
            <input type="password" class="form-control" placeholder="Password" name="studentPassword" required>
        </div>
        <div class="form-group">
            <label for="studentName">Name *</label>
            <input type="text" class="form-control" placeholder="Name" name="studentName" required>
        </div>
        <div class="form-group">
            <label for="studentPhoneNumber">Phone Number *</label>
            <input type="text" class="form-control" placeholder="Phone Number" name="studentPhoneNumber" required>
        </div>
        <div class="form-group">
            <label for="studentPostalAddress">Postal Address *</label>
            <input type="text" class="form-control" placeholder="Postal Address" name="studentPostalAddress" required>
        </div>
        <input type="submit" class="btn btn-secondary" name="editStudentButton" value="Edit">
        <input type="submit" class="btn btn-danger" name="deleteStudentButton" value="Delete">
    </form>
<?php
} elseif ($userTableDataSet->checkIfEmployer($_SESSION['user_id'])) {
?>
<h2>Employer</h2>
    <form method="post" action="" class="form text-primary" enctype="multipart/form-data">
        <div class="form-group">
            <label for="employerEmail">Email *</label>
            <input type="email" class="form-control" placeholder="Email" name="employerEmail" readonly>
        </div>
        <div class="form-group">
            <label for="employerPassword">Password *</label>
            <input type="password" class="form-control" placeholder="Password" name="employerPassword">
        </div>
        <div class="form-group">
            <label for="employerContactName">Contact Name *</label>
            <input type="text" class="form-control" placeholder="Name" name="employerContactName">
        </div>
        <div class="form-group">
            <label for="employerCompanyName">Company Name *</label>
            <input type="text" class="form-control" placeholder="Name" name="employerCompanyName" readonly>
        </div>
        <div class="form-group">
            <label for="employerPhoneNumber">Phone Number *</label>
            <input type="text" class="form-control" placeholder="Phone Number" name="employerPhoneNumber">
        </div>
        <div class="form-group">
            <label for="employerPostalAddress">Postal Address *</label>
            <input type="text" class="form-control" placeholder="Postal Address" name="employerPostalAddress">
        </div>
        <input type="submit" class="btn btn-secondary" name="editEmployerButton" value="Edit">
        <input type="submit" class="btn btn-danger" name="deleteEmployerButton" value="Delete">
    </form>
<?php
}
if (isset($_SESSION["editProfileError"]))
{
echo "<p class='error'>" . $_SESSION["editProfileError"] . "</p>";
unset($_SESSION["editProfileError"]);
}
?>

<?php require('template/footer.phtml') ?>
