<?php require("template/header.phtml") ?>

<?php

if (!isset($_SESSION["login"])) {
    echo ' 
            <form method="post" action="" class="form text-primary">
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="text" class="form-control" placeholder="Email" name="email" required>
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" placeholder="password" name="password" required>
                </div>
                <input type="submit" class="btn btn-primary" name="loginbutton" value="Login">
            </form>';
    if (isset($_SESSION["loginError"]))
    {
        echo "<p class='error'>" . $_SESSION["loginError"] . "</p>";
        unset($_SESSION["loginError"]);
    }
}
else
{
    if($userTableDataSet->checkIfStudent($_SESSION['user_id']))
    {
        echo '
               <h2>Matching</h2>

                <div class="container">
                    <div class="row">
                        <div class="col d-flex justify-content-center">
                            <form method="post" class="form text-primary">
                                <input type="submit" class="btn btn-secondary" name="matchingNo" value="No">
                            </form>
                         </div>
                        <div class="col-8 d-flex justify-content-center">

                        </div>
                        <div class="col d-flex justify-content-center">
                            <form method="post" class="form text-primary">
                                <input type="submit" class="btn btn-secondary" name="matchingYes" value="Yes">
                            </form>
                        </div>
                    </div>
                </div>
               ';
    }
    else if($userTableDataSet->checkIfEmployer($_SESSION['user_id']))
    {
        echo '<p>Logged in as Employer</p>';
    }
}
?>

<?php require("template/footer.phtml") ?>
