<?php require("template/header.phtml") ?>

<?php

if (!isset($_SESSION["login"])) {
    echo ' 
            <form method="post" action="" class="form text-primary">
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="text" class="form-control" placeholder="Email" name="email" required>
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" placeholder="password" name="password" required>
                </div>
                <input type="submit" class="btn btn-primary" name="loginbutton" value="Login">
            </form>';
    if (isset($_SESSION["loginError"]))
    {
        echo "<p class='error'>" . $_SESSION["loginError"] . "</p>";
        unset($_SESSION["loginError"]);
    }
}
else
{
    if($userTableDataSet->checkIfStudent($_SESSION['user_id']))
    {
        ?>
               <h2>Matching</h2>

                <div class="container">
                    <div class="row">
                        <div class="col d-flex justify-content-center">
                            <form method="post" class="form text-primary">
                                <input type="submit" class="btn btn-secondary" name="studentMatchingNo" value="No">
                            </form>
                         </div>
                        <div class="col-8 justify-content-center" style="height: 69vh">
                            <p>Description: Software Engineer</p>
                            <br>
                            <p>Skills Required: Passionate, Experienced, Excellent understanding of Agile, Leadership experience, Strong Communication skills</p>
                            <br>
                            <p>Salary: £50,000</p>
                            <br>
                            <p>Location: Manchester</p>
                            <br>
                            <p>Start and End Date: 30/01/2022   |  30/01/2022</p>
                            <br>
                            <p>Type: Computer Science</p>
                        </div>
                        <div class="col d-flex justify-content-center">
                            <form method="post" class="form text-primary">
                                <input type="submit" class="btn btn-secondary" name="studentMatchingYes" value="Yes">
                            </form>
                        </div>
                    </div>
                </div>
        <?php
    }
    else if($userTableDataSet->checkIfEmployer($_SESSION['user_id']))
    {
        ?>
               <h2>Matching</h2>

                <div class="container">
                    <div class="row">
                        <div class="col d-flex justify-content-center">
                            <form method="post" class="form text-primary">
                                <input type="submit" class="btn btn-secondary" name="employerMatchingNo" value="No">
                            </form>
                         </div>
                        <div class="col-8 d-flex justify-content-center">
                            <embed src="/images/brief.pdf" width="800vw" height="1000vh" />
                        </div>
                        <div class="col d-flex justify-content-center">
                            <form method="post" class="form text-primary">
                                <input type="submit" class="btn btn-secondary" name="employerMatchingYes" value="Yes">
                            </form>
                        </div>
                    </div>
                </div>
        <?php
    }
}
?>

<?php require("template/footer.phtml") ?>
