<?php require("template/header.phtml") ?>

<?php

if (!isset($_SESSION["login"])) {
    echo ' 
            <form method="post" action="" class="form text-primary">
                <div class="form-group">
                    <label for="userID">UserID</label>
                    <input type="text" class="form-control" placeholder="UserID" name="userID" required>
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" placeholder="password" name="password" required>
                </div>
                <input type="submit" class="btn btn-primary" name="loginbutton" value="Login">
            </form>';
    if (isset($_SESSION["error"]))
    {
        echo "<p class='error'>" . $_SESSION["error"] . "</p>";
        unset($_SESSION["error"]);
    }
}
else
{
    echo '
            <form method="post" action="" class="form text-primary">
                <label>Logged in as ' . $_SESSION["login"] . '</label>
                <input type="submit" class="btn btn-danger" name="logoutbutton" value="Logout">
            </form>';
}
?>

<?php require("template/footer.phtml") ?>
