<?php require('template/header.phtml') ?>

<h2>Matching</h2>

<div class="container">
    <div class="row">
        <div class="col d-flex justify-content-center">
            <form method="post" class="form text-primary">
                <input type="submit" class="btn btn-secondary" name="matchingNo" value="No">
            </form>
        </div>
        <div class="col-8 d-flex justify-content-center">

        </div>
        <div class="col d-flex justify-content-center">
            <form method="post" class="form text-primary">
                <input type="submit" class="btn btn-secondary" name="matchingYes" value="Yes">
            </form>
        </div>
    </div>
</div>


<?php require('template/footer.phtml') ?>
