<?php require('template/header.phtml') ?>

<h2>Student</h2>
<form method="post" action="" class="form text-primary">
    <div class="form-group">
        <label for="studentUserID">UserID *</label>
        <input type="text" class="form-control" placeholder="UserID" name="userID" required>
    </div>
    <div class="form-group">
        <label for="password">Password *</label>
        <input type="password" class="form-control" placeholder="Password" name="password" required>
    </div>
    <div class="form-group">
        <label for="studentName">Name *</label>
        <input type="text" class="form-control" placeholder="Name" name="studentName" required>
    </div>
    <div class="form-group">
        <label for="studentEmail">Email *</label>
        <input type="email" class="form-control" placeholder="Email" name="studentEmail" required>
    </div>
    <div class="form-group">
        <label for="studentPhoneNumber">Phone Number *</label>
        <input type="text" class="form-control" placeholder="Phone Number" name="studentPhoneNumber" required>
    </div>
    <div class="form-group">
        <label for="studentPostalAddress">Postal Address *</label>
        <input type="text" class="form-control" placeholder="Postal Address" name="studentPostalAddress" required>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm d-flex justify-content-center">
                <input type="submit" class="btn btn-secondary" name="registerStudentButton" value="Register as Student">
            </div>
            <div class="col-sm d-flex justify-content-center">
                <input type="submit" class="btn btn-secondary" name="registerEmployerButton" value="Register as Employer">
            </div>
        </div>
    </div>
</form>
<?php
if (isset($_SESSION["registerError"]))
{
echo "<p class='error'>" . $_SESSION["registerError"] . "</p>";
unset($_SESSION["registerError"]);
}
?>

<?php require('template/footer.phtml') ?>
