<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="css/bootstrap-theme.css" rel="stylesheet">
    <link href="css/my-style.css" rel="stylesheet">

    <title>HackCamp Group 18 - <?php echo $view->pageTitle; ?></title>
</head>

<body role=""document">

<div class="container">
    <div class="row">
        <!--  <img id="logo" src="images/" alt="Logo Image" />  -->
        <div id="title" class="col-xs-12">
            <div id="logo-text" class="pull-right"> <h1>HackCamp group 18</h1> </div>
            <div class="pull-right"> <h2><?php echo $view->pageTitle ?> </h2></div>
        </div>
    </div>

    <div class="row">
        <div id="menu" class="col-xs-6 col-sm-3 col-md-2">
        <ul class="nav navbar_default nav-stacked">

        </ul>
            <?php
            if (isset($_SESSION["login"])) {
            echo '
            <form method="post" action="" class="form text-primary">
                <label>Logged in as ' . $_SESSION["login"] . '</label>
                <input type="submit" class="btn btn-danger" name="logoutbutton" value="Logout">
            </form>';
            }
            ?>

            <li><a href="index.php">Login</a></li>
            <li><a href="register.php">Register</a></li>
            <li><a href="#">Edit Profile</a></li>
            <li><a href="#">Matching</a></li>
            <li><a href="#">Applied Students (Only Visible for Logged in Staff Accounts)</a></li>
        </ul>
        </div>
    <div id="content" class="col-xs-6 col-sm-9 col-md-10">