<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="css/bootstrap-theme.css" rel="stylesheet">
    <link href="css/my-style.css" rel="stylesheet">

    <title>BCS Placements - <?php echo $view->pageTitle; ?></title>
</head>

<body role="document">

<div class="container-fluid">
    <div class="row">
        <div id="title" class="col-xs-12">
            <div id="logo-text" class="pull-right"> <h1>BCS Placements</h1> </div>
            <div class="pull-right"> <h2><?php echo $view->pageTitle ?> </h2></div>
        </div>
    </div>

    <div class="row">
        <div id="menu" class="col-xs-6 col-sm-3 col-md-2">
            <?php
            if ($_SESSION['user']->getLogStatus()) {
                echo '
            <form method="post" action="" class="form text-primary">
                <label>Logged in as ' . $_SESSION["login"] . '</label>';
                if ($userTableDataSet->checkIfEmployer($_SESSION['user_id'])) {
                    echo '<label>Logged in as Employer</label>';
                }
                elseif ($userTableDataSet->checkIfStudent($_SESSION['user_id']))
                {
                    echo '<label>Logged in as Student</label>';
                }
                echo '
                <input type="submit" class="btn btn-danger" name="logoutbutton" value="Logout">
            </form>';
            }

            if ($_SESSION['user']->getLogStatus()) {
                if ($userTableDataSet->checkIfEmployer($_SESSION['user_id'])) {
                    echo '<li><a href = "createplacement.php" > Create Placement </a ></li>';
                    echo '<li><a href = "#" > Edit Profile </a ></li>';
                    echo '<li><a href = "#" > Applied Students(Only Visible for Logged in Staff Accounts)</a ></li>';
                }
                elseif ($userTableDataSet->checkIfStudent($_SESSION['user_id']))
                {
                    echo '<li><a href = "#" > Edit CV </a ></li>';
                }
            } else {
                echo '<li><a href = "index.php" > Login</a ></li>';
                echo '<li><a href = "register.php" > Register</a ></li>';
            }
            ?>
        </div>
    <div id="content" class="col-xs-6 col-sm-9 col-md-10">